#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""remi-pipecat - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Openai (Speech-to-Text)
- Openai (LLM)
- Openai (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import os

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.frames.frames import LLMRunFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.runner import PipelineRunner
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.types import RunnerArguments, SmallWebRTCRunnerArguments
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.services.openai.stt import OpenAISTTService
from pipecat.services.openai.tts import OpenAITTSService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport

load_dotenv(override=True)


def _first_non_empty(*values: str | None) -> str | None:
    for value in values:
        if value is not None and str(value).strip():
            return str(value).strip()
    return None


def _looks_like_dashscope(url: str | None) -> bool:
    if not url:
        return False
    u = url.lower()
    return "dashscope.aliyuncs.com" in u or "dashscope-intl.aliyuncs.com" in u


async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")

    # Split config by capability:
    # - LLM can use DashScope OpenAI-compatible endpoint.
    # - STT/TTS currently need providers that implement OpenAI audio endpoints.
    llm_api_key = _first_non_empty(os.getenv("OPENAI_LLM_API_KEY"), os.getenv("OPENAI_API_KEY"))
    llm_base_url = _first_non_empty(os.getenv("OPENAI_LLM_BASE_URL"), os.getenv("OPENAI_BASE_URL"))
    llm_model = _first_non_empty(os.getenv("OPENAI_LLM_MODEL"), os.getenv("OPENAI_MODEL"), "gpt-4.1")

    stt_api_key = _first_non_empty(os.getenv("OPENAI_STT_API_KEY"), os.getenv("OPENAI_API_KEY"))
    stt_base_url = _first_non_empty(os.getenv("OPENAI_STT_BASE_URL"), os.getenv("OPENAI_BASE_URL"))
    stt_model = _first_non_empty(
        os.getenv("OPENAI_STT_MODEL"),
        os.getenv("OPENAI_TRANSCRIBE_MODEL"),
        "gpt-4o-transcribe",
    )

    tts_api_key = _first_non_empty(os.getenv("OPENAI_TTS_API_KEY"), os.getenv("OPENAI_API_KEY"))
    tts_base_url = _first_non_empty(os.getenv("OPENAI_TTS_BASE_URL"), os.getenv("OPENAI_BASE_URL"))
    tts_model = _first_non_empty(os.getenv("OPENAI_TTS_MODEL"), "gpt-4o-mini-tts")

    if not llm_api_key:
        raise RuntimeError("缺少 LLM API Key：请设置 OPENAI_LLM_API_KEY（或 OPENAI_API_KEY）。")
    if not stt_api_key:
        raise RuntimeError("缺少 STT API Key：请设置 OPENAI_STT_API_KEY（或 OPENAI_API_KEY）。")
    if not tts_api_key:
        raise RuntimeError("缺少 TTS API Key：请设置 OPENAI_TTS_API_KEY（或 OPENAI_API_KEY）。")

    if _looks_like_dashscope(stt_base_url) or _looks_like_dashscope(tts_base_url):
        raise RuntimeError(
            "当前配置会导致 404：DashScope OpenAI 兼容端点不支持 OpenAI STT/TTS 的 "
            "/audio/transcriptions 与 /audio/speech。"
            "请将 OPENAI_STT_BASE_URL / OPENAI_TTS_BASE_URL 指向支持这些端点的提供方 "
            "(例如 https://api.openai.com/v1)，或改用其他 STT/TTS 服务。"
        )

    # Speech-to-Text service
    stt = OpenAISTTService(
        api_key=stt_api_key,
        base_url=stt_base_url,
        settings=OpenAISTTService.Settings(model=stt_model),
    )

    # Text-to-Speech service
    tts = OpenAITTSService(
        api_key=tts_api_key,
        base_url=tts_base_url,
        settings=OpenAITTSService.Settings(
            model=tts_model,
            voice=os.getenv("OPENAI_VOICE_ID"),
        ),
    )

    # LLM service
    llm = OpenAILLMService(
        api_key=llm_api_key,
        base_url=llm_base_url,
        settings=OpenAILLMService.Settings(
            model=llm_model,
            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can't be spoken. Respond to what the user said in a creative, helpful, and brief way.",
        ),
    )

    context = LLMContext()
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(),
        ),
    )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            user_aggregator,
            llm,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[],
    )

    @task.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation
        context.add_message({"role": "user", "content": "Please introduce yourself."})
        await task.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()

    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport = None

    match runner_args:
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    await run_bot(transport)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
